<?php 
/**
	Admin Page Framework v3.8.20 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/LazyCoalaCodes>
	Copyright (c) 2013-2019, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class LazyCoala_AdminPageFramework_Form_View___CSS_term_meta extends LazyCoala_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".LazyCoalaCodes-form-table-outer-row-term_meta,.LazyCoalaCodes-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.LazyCoalaCodes-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.LazyCoalaCodes-form-table-term_meta .LazyCoalaCodes-sectionset,.LazyCoalaCodes-form-table-term_meta .LazyCoalaCodes-section {margin-bottom: 0;}.LazyCoalaCodes-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.LazyCoalaCodes-form-table-term_meta.add-new-term .LazyCoalaCodes-section .form-table > tbody > tr > td,.LazyCoalaCodes-form-table-term_meta.add-new-term .LazyCoalaCodes-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.LazyCoalaCodes-form-table-term_meta.add-new-term .LazyCoalaCodes-field {width: auto;}.LazyCoalaCodes-form-table-term_meta.add-new-term .LazyCoalaCodes-field {max-width: 100%;}.LazyCoalaCodes-form-table-term_meta.add-new-term .sortable .LazyCoalaCodes-field {width: auto;} .LazyCoalaCodes-form-table-term_meta.add-new-term .LazyCoalaCodes-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.LazyCoalaCodes-form-table-term_meta .LazyCoalaCodes-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.LazyCoalaCodes-form-table-term_meta .LazyCoalaCodes-collapsible-title h3 {margin: 0;}.LazyCoalaCodes-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.LazyCoalaCodes-form-table-term_meta .LazyCoalaCodes-section-tab h4 {margin: 0;} ";
    }
    }
    