<?php 
/**
	Admin Page Framework v3.8.20 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/LazyCoalaCodes>
	Copyright (c) 2013-2019, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class LazyCoala_AdminPageFramework_MetaBox_Model___PostMeta extends LazyCoala_AdminPageFramework_Factory_Model___Meta_Base {
    }
    